source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Async_Example', :exclusive => true do
  pod 'SwiftAsync', :path => '../'
  pod 'ReactiveUI'
end

target 'Async_Tests', :exclusive => true do
  pod 'SwiftAsync', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
